name: Manual destroy

on:
  workflow_dispatch:

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS}}
          aws_default_region: us-east-1

          # Provide a secret called `DOT_ENV` to append environment variables to the .env file
          env_ghs: ${{ secrets.DOT_ENV }}

          aws_r53_enable: true
          aws_r53_create_sub_cert: true
          aws_r53_domain_name: bitovi-jira.com
          aws_r53_sub_domain_name: auto-scheduler
          aws_elb_app_port: 3000

          aws_ec2_instance_type: t3.small

          docker_cloudwatch_enable: true
          docker_cloudwatch_retention_days: 7

          tf_stack_destroy: true
          tf_state_bucket_destroy: true
